name: JapanTV
options:
  deploymentTarget:
    tvOS: "17.0"
settings:
  base:
    SWIFT_VERSION: 6.0
targets:
  JapanTV:
    type: application
    platform: tvOS
    deploymentTarget: "17.0"
    sources:
      - path: JapanTV
    configFiles:
      Debug: config/Signing.xcconfig
      Release: config/Signing.xcconfig
    dependencies:
      - framework: Vendor/TVVLCKit.xcframework
        embed: true
    settings:
      base:
        PRODUCT_NAME: $(TARGET_NAME)
        PRODUCT_BUNDLE_IDENTIFIER: com.example.japantv
        INFOPLIST_FILE: JapanTV/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SUPPORTS_MACCATALYST: NO
        SWIFT_ENABLE_EXPLICIT_MODULES: NO
