#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL_XCCONFIG="$ROOT_DIR/config/Signing.local.xcconfig"
LOCAL_ENV="$ROOT_DIR/.local/apple-tv.env"

TEAM_ID=""
TEAM_NAME=""
APPLE_TV_DEVICE=""
APP_BUNDLE_ID="com.example.japantv"

usage() {
  cat <<USAGE
Usage:
  $(basename "$0") --team-id <TEAM_ID> --team-name <TEAM_NAME> [--device <DEVICE>] [--bundle-id <BUNDLE_ID>]

Arguments:
  --team-id      Apple Developer Team ID (required)
  --team-name    Apple Developer Team Name (required)
  --device       Apple TV device identifier or name for devicectl install (optional)
  --bundle-id    App bundle identifier for launch step (default: com.example.japantv)
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --team-id)
      TEAM_ID="$2"
      shift 2
      ;;
    --team-name)
      TEAM_NAME="$2"
      shift 2
      ;;
    --device)
      APPLE_TV_DEVICE="$2"
      shift 2
      ;;
    --bundle-id)
      APP_BUNDLE_ID="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1"
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$TEAM_ID" || -z "$TEAM_NAME" ]]; then
  echo "Both --team-id and --team-name are required."
  usage
  exit 1
fi

mkdir -p "$ROOT_DIR/config" "$ROOT_DIR/.local"

cat > "$LOCAL_XCCONFIG" <<XCCONFIG
// Generated by scripts/configure-local-signing.sh
DEVELOPMENT_TEAM = $TEAM_ID
JAPANTV_APPLE_TEAM_NAME = $TEAM_NAME
XCCONFIG

cat > "$LOCAL_ENV" <<ENVFILE
# Generated by scripts/configure-local-signing.sh
APPLE_TEAM_ID='$TEAM_ID'
APPLE_TEAM_NAME='$TEAM_NAME'
APPLE_TV_DEVICE='$APPLE_TV_DEVICE'
APP_BUNDLE_ID='$APP_BUNDLE_ID'
ENVFILE

echo "Wrote local signing config: $LOCAL_XCCONFIG"
echo "Wrote local Apple TV deploy config: $LOCAL_ENV"
echo "These files are gitignored."
